# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: '3'

tasks:
  build:
    requires:
      vars: [recipe]
    cmd: >
      bluebuild generate ./recipes/{{ .recipe }}.yml
      | docker build -f - --platform=linux/amd64 .
