---
name: build-disk-images
on:
  workflow_dispatch:

jobs:
  build-containers:
    name: Build Disk Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - steamdeck
          - tablet
          - router
          - workstation
          - htpc
    steps:
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Setup Image Builder Config
        run: echo "$IMAGE_BUILDER_CONFIG" > ./config.toml
        env:
          IMAGE_BUILDER_CONFIG: ${{ secrets.IMAGE_BUILDER_CONFIG }}

      - name: Build qcow image
        run: |
          docker run --rm \
          --privileged \
          --security-opt label=type:unconfined_t \
          -v $(pwd)/config.toml:/config.toml:ro \
          -v $(pwd)/output:/output \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --type qcow2 \
          --rootfs xfs \
          --output /output \
          ghcr.io/kevindurb/${{ matrix.recipe }}

      - name: Upload image as artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.recipe }}.qcow2
          path: |
            ./output/disk.qcow2
          if-no-files-found: error
          retention-days: 0
          compression-level: 0
