---
name: build-containers
on:
  pull_request:
    branches:
      - main
  schedule:
    # 10:05am UTC everyday
    - cron: '05 10 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

jobs:
  build-containers:
    name: Build Containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - steamdeck
          - tablet
          - router
          - workstation
          - htpc
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.6.1
        with:
          recipe: ${{ matrix.recipe }}.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true

      - name: Setup Image Builder Config
        run: echo "$IMAGE_BUILDER_CONFIG" > ./config.toml
        env:
          IMAGE_BUILDER_CONFIG: ${{ secrets.IMAGE_BUILDER_CONFIG }}

      - name: Build qcow image
        run: |
          docker run --rm \
          --privileged \
          --security-opt lable=type:unconfined_t \
          -v $(pwd)/config.toml:/config.toml:ro \
          quay.io/centos-bootc/bootc-image-builder:latest \
          --type qcow2 \
          ghcr.io/kevindurb/${{ matrix.recipe }}
